# Generated by Django 5.1.6 on 2025-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('wallet_address', models.CharField(max_length=255)),
                ('from_currency', models.CharField(max_length=50)),
                ('to_currency', models.CharField(max_length=50)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
