# Generated by Django 5.1.6 on 2025-04-27 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_created_at_alter_order_from_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
