# Generated by Django 5.1.6 on 2025-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_from_amount_remove_order_to_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto')], max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
