# Generated by Django 5.1.6 on 2025-04-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paymentdetails'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
    ]
