# Generated by Django 5.1.6 on 2025-04-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey(blank=True, db_column='payment_details_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paymentdetails'),
        ),
    ]
