# Generated by Django 5.1.6 on 2025-04-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey('PaymentDetails', on_delete=models.SET_NULL, null=True, blank=True),
        )
    ]
