# Generated by Django 5.1.6 on 2025-05-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_additional_data_alter_order_payment_details_and_more'),
    ]
    
    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='additional_data',
            new_name='wallet_address',
        ),
    ]


