# Generated by Django 5.1.6 on 2025-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
