# Generated by Django 5.1.6 on 2025-05-01 19:25

from uuid import uuid4
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
