# Generated by Django 5.1.6 on 2025-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(editable=False, max_length=32, null=True, unique=True),
        ),
    ]
