# Generated by Django 5.1.6 on 2025-05-01 20:20

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_order_uuid_order_client_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(default=main.models.generate_so_fucking_short_unique_id, max_length=8, unique=True),
        ),
    ]
